version: '3'

services:
  # USŁUGA 1: Twoja aplikacja (Backend)
  app:
    # Pobieramy Twój gotowy obraz z Docker Hub
    image: arko2811/flask-devops-app:latest
    container_name: flask-backend
    restart: always
    # UWAGA: Nie wystawiamy tutaj "ports", bo nie chcemy,
    # żeby ktoś łączył się bezpośrednio z Pythonem.
    # Nginx będzie jedynym wejściem.

  # USŁUGA 2: Serwer WWW (Frontend/Proxy)
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80" # Wystawiamy port 80 na świat
    volumes:
      # Wstrzykujemy nasz plik konfiguracyjny do kontenera
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app # Nginx wystartuje dopiero, jak App będzie gotowa